"""
flutterwave.py — KWallet Flutterwave integration.

Supports:
  - Card deposits (Rave inline / hosted payment link)
  - Bank transfer deposits (virtual account / pay-by-transfer)
  - Mobile Money deposits (M-Pesa, Airtel via Flutterwave)
  - Payouts / disbursements (bank transfer out, mobile money out)

Security mirrors mpesa.py / airtel.py:
  Risk #02: idempotency key on every transaction
  Risk #05: webhook verified with HMAC-SHA256 (FLW-Secret-Hash header)
  Risk #07: SSL always verified
  Risk #08: rate-limiting handled in views, not here
  Risk #10: token not needed — Flutterwave uses a static secret key
"""

import hashlib
import hmac
import logging
import uuid

import requests
from django.conf import settings
from django.utils import timezone

logger = logging.getLogger(__name__)

FLW_CONFIG = getattr(settings, 'FLUTTERWAVE_CONFIG', {})

# Flutterwave published webhook IP ranges — verify from FLW docs periodically
FLW_WEBHOOK_IP_RANGES = [
    '52.46.138.',   # AWS us-east-1 (FLW primary)
    '54.144.',
    '18.214.',
    '34.193.',
]

# Supported deposit channels
CHANNEL_CARD         = 'card'
CHANNEL_BANK_TRANSFER = 'banktransfer'
CHANNEL_MPESA        = 'mpesa'
CHANNEL_AIRTEL       = 'airtel'

# Supported payout types
PAYOUT_BANK   = 'account'
PAYOUT_MOBILE = 'mobile_money_ke'


class FlutterwaveClient:
    BASE_URL = 'https://api.flutterwave.com/v3'

    def __init__(self):
        cfg = FLW_CONFIG
        self.secret_key     = cfg.get('SECRET_KEY', '')
        self.public_key     = cfg.get('PUBLIC_KEY', '')
        self.encryption_key = cfg.get('ENCRYPTION_KEY', '')
        self.webhook_secret = cfg.get('WEBHOOK_SECRET', '')
        self.redirect_url   = cfg.get('REDIRECT_URL', '')
        self.use_mock       = cfg.get('USE_MOCK', False)

        # Risk #07: SSL always verified
        self.verify_ssl = not cfg.get('DEV_DISABLE_SSL', False)
        if not self.verify_ssl:
            logger.warning('FLW SSL verification disabled via DEV_DISABLE_SSL — never use in production!')

    def _headers(self):
        return {
            'Authorization': f'Bearer {self.secret_key}',
            'Content-Type':  'application/json',
        }

    def _post(self, path: str, payload: dict) -> dict:
        resp = requests.post(
            f'{self.BASE_URL}{path}',
            json=payload,
            headers=self._headers(),
            verify=self.verify_ssl,
            timeout=30,
        )
        resp.raise_for_status()
        return resp.json()

    def _get(self, path: str, params: dict = None) -> dict:
        resp = requests.get(
            f'{self.BASE_URL}{path}',
            params=params or {},
            headers=self._headers(),
            verify=self.verify_ssl,
            timeout=15,
        )
        resp.raise_for_status()
        return resp.json()

    # ─────────────────────────────────────────────
    # Deposits — initiate payment
    # ─────────────────────────────────────────────

    def create_payment_link(
        self,
        amount: float,
        currency: str,
        customer_email: str,
        customer_name: str,
        customer_phone: str,
        tx_ref: str,
        description: str = 'KWallet Deposit',
        payment_options: str = 'card,banktransfer,mpesa,airtel',
    ) -> dict:
        """
        Create a hosted payment link (Rave Standard).
        Returns {'status': 'success', 'link': '<url>'}.
        The user is redirected to this URL to complete payment.
        On completion Flutterwave redirects to REDIRECT_URL with tx_ref + transaction_id.
        Risk #02: tx_ref is our idempotency key — generated by caller.
        """
        if self.use_mock:
            return {
                'status':  'success',
                'message': 'Hosted Link',
                'data': {
                    'link': f'https://mock.flutterwave.com/pay/{tx_ref}',
                },
                'mock': True,
            }

        payload = {
            'tx_ref':          tx_ref,
            'amount':          str(amount),
            'currency':        currency,
            'redirect_url':    self.redirect_url,
            'payment_options': payment_options,
            'customer': {
                'email':       customer_email,
                'name':        customer_name,
                'phonenumber': customer_phone,
            },
            'customizations': {
                'title':       'KWallet',
                'description': description,
                'logo':        FLW_CONFIG.get('LOGO_URL', ''),
            },
        }
        data = self._post('/payments', payload)
        return data

    def initiate_mobile_money(
        self,
        phone: str,
        amount: float,
        currency: str,
        tx_ref: str,
        network: str = 'mpesa',   # 'mpesa' | 'airtel'
        email: str = 'noreply@kwallet.ke',
    ) -> dict:
        """
        Initiate a direct mobile-money STK push via Flutterwave.
        Supports M-Pesa (network='mpesa') and Airtel Money (network='airtel').
        Risk #02: tx_ref is the idempotency key.
        """
        if self.use_mock:
            return {
                'status':  'success',
                'message': 'Charge initiated',
                'meta': {'authorization': {'mode': 'redirect', 'redirect': f'https://mock.flw/{tx_ref}'}},
                'mock': True,
            }

        payload = {
            'phone_number': phone,
            'amount':       str(amount),
            'currency':     currency,
            'email':        email,
            'tx_ref':       tx_ref,
            'network':      network.upper(),
        }
        return self._post('/charges?type=mobile_money_kenya', payload)

    # ─────────────────────────────────────────────
    # Verify payment
    # ─────────────────────────────────────────────

    def verify_transaction(self, transaction_id: str) -> dict:
        """
        Verify a completed transaction by Flutterwave transaction ID.
        Always call this before crediting a wallet — never trust the
        redirect / webhook payload alone (Risk #02 / defence-in-depth).
        """
        if self.use_mock:
            return {
                'status': 'success',
                'data': {
                    'id':       transaction_id,
                    'tx_ref':   f'mock_{transaction_id}',
                    'status':   'successful',
                    'amount':   100,
                    'currency': 'KES',
                    'mock':     True,
                },
            }
        return self._get(f'/transactions/{transaction_id}/verify')

    def verify_transaction_by_ref(self, tx_ref: str) -> dict:
        """
        Look up a transaction by our own tx_ref (idempotency key).
        Use when the webhook only gives us tx_ref, not the FLW id.
        """
        if self.use_mock:
            return {
                'status': 'success',
                'data': [{
                    'id':     'mock_001',
                    'tx_ref': tx_ref,
                    'status': 'successful',
                    'amount': 100,
                    'currency': 'KES',
                    'mock': True,
                }],
            }
        return self._get('/transactions', params={'tx_ref': tx_ref})

    # ─────────────────────────────────────────────
    # Payouts / Disbursements
    # ─────────────────────────────────────────────

    def initiate_transfer(
        self,
        account_bank: str,
        account_number: str,
        amount: float,
        currency: str,
        narration: str,
        reference: str,
        beneficiary_name: str = '',
        destination_branch_code: str = '',
    ) -> dict:
        """
        Bank transfer payout (B2C to bank account).
        Risk #02: reference is our idempotency key.
        """
        if self.use_mock:
            return {
                'status':  'success',
                'message': 'Transfer Queued',
                'data': {
                    'id':        f'mock_trf_{reference}',
                    'reference': reference,
                    'status':    'NEW',
                    'mock':      True,
                },
            }

        payload = {
            'account_bank':     account_bank,
            'account_number':   account_number,
            'amount':           str(amount),
            'narration':        narration,
            'currency':         currency,
            'reference':        reference,
            'callback_url':     FLW_CONFIG.get('TRANSFER_CALLBACK_URL', ''),
            'debit_currency':   currency,
        }
        if beneficiary_name:
            payload['beneficiary_name'] = beneficiary_name
        if destination_branch_code:
            payload['destination_branch_code'] = destination_branch_code

        return self._post('/transfers', payload)

    def initiate_mobile_money_payout(
        self,
        phone: str,
        amount: float,
        currency: str,
        narration: str,
        reference: str,
        network: str = 'mpesa',   # 'mpesa' | 'airtel'
    ) -> dict:
        """
        Mobile money payout (B2C disbursement via Flutterwave).
        Risk #02: reference is idempotency key.
        """
        if self.use_mock:
            return {
                'status':  'success',
                'message': 'Transfer Queued',
                'data': {
                    'id':        f'mock_mob_{reference}',
                    'reference': reference,
                    'status':    'NEW',
                    'mock':      True,
                },
            }

        # Flutterwave mobile money payout uses /transfers with mobile_number
        payload = {
            'account_bank':   network.upper(),
            'account_number': phone,
            'amount':         str(amount),
            'narration':      narration,
            'currency':       currency,
            'reference':      reference,
            'callback_url':   FLW_CONFIG.get('TRANSFER_CALLBACK_URL', ''),
        }
        return self._post('/transfers', payload)

    def get_transfer_status(self, transfer_id: str) -> dict:
        """Poll transfer status by Flutterwave transfer ID."""
        if self.use_mock:
            return {
                'status': 'success',
                'data': {'id': transfer_id, 'status': 'SUCCESSFUL', 'mock': True},
            }
        return self._get(f'/transfers/{transfer_id}')

    # ─────────────────────────────────────────────
    # Webhook security (Risk #05)
    # ─────────────────────────────────────────────

    def verify_webhook_signature(self, payload_bytes: bytes, signature_header: str) -> bool:
        """
        Risk #05: Verify the FLW-Signature (or verif-hash / secret-hash header).
        Flutterwave sends the WEBHOOK_SECRET as a plain header 'verif-hash'.
        Compare with constant-time compare_digest to prevent timing attacks.
        """
        expected = self.webhook_secret
        if not expected:
            logger.warning('FLUTTERWAVE WEBHOOK_SECRET not set — webhook endpoint unprotected!')
            return self.use_mock

        # Flutterwave uses a direct secret header (not HMAC-SHA256 over body)
        # For extra security you may also verify an HMAC if configured
        return hmac.compare_digest(signature_header, expected)

    def verify_webhook_ip(self, ip: str) -> bool:
        """Risk #05: IP allowlist for Flutterwave webhook callbacks."""
        if self.use_mock:
            return True
        allowed = FLW_CONFIG.get('ALLOWED_WEBHOOK_IPS', FLW_WEBHOOK_IP_RANGES)
        if not allowed:
            logger.warning('No Flutterwave webhook IP allowlist configured!')
            return False
        return any(ip.startswith(prefix) for prefix in allowed)
