# Generated by Django 4.2.7 on 2026-06-01 04:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # WalletUser MUST be created first: Django's admin/auth apps resolve
        # their swappable_dependency on AUTH_USER_MODEL to wallet's
        # ('wallet', '__first__') migration, i.e. THIS file. If WalletUser
        # isn't created here, admin.0001_initial tries to FK into a table
        # that doesn't exist yet and migrate fails (the original bug).
        migrations.CreateModel(
            name='WalletUser',
            fields=[
                ('id',                    models.BigAutoField(primary_key=True, serialize=False)),
                ('password',              models.CharField(max_length=255)),
                ('last_login',            models.DateTimeField(null=True, blank=True)),
                ('phone',                 models.CharField(max_length=20, unique=True)),
                ('first_name',            models.CharField(max_length=80, blank=True)),
                ('last_name',             models.CharField(max_length=80, blank=True)),
                ('is_active',             models.BooleanField(default=True)),
                ('is_staff',              models.BooleanField(default=False)),
                ('is_superuser',          models.BooleanField(default=False)),
                ('date_joined',           models.DateTimeField(default=django.utils.timezone.now)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until',          models.DateTimeField(null=True, blank=True)),
            ],
            options={'verbose_name': 'User'},
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('country', models.CharField(choices=[('KE', 'Kenya'), ('TZ', 'Tanzania'), ('UG', 'Uganda'), ('RW', 'Rwanda'), ('ET', 'Ethiopia')], default='KE', max_length=2)),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('legacy_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('mpesa_deposit', 'M-Pesa Deposit'), ('mpesa_withdraw', 'M-Pesa Withdrawal'), ('mtn_deposit', 'MTN MoMo Deposit'), ('mtn_withdraw', 'MTN MoMo Withdrawal'), ('airtel_deposit', 'Airtel Deposit'), ('airtel_withdraw', 'Airtel Withdrawal'), ('bank_deposit', 'Bank Deposit'), ('bank_withdraw', 'Bank Withdrawal'), ('exchange', 'Currency Exchange'), ('p2p_send', 'P2P Send'), ('p2p_receive', 'P2P Receive'), ('fee', 'Platform Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('details', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('in', 'Deposit'), ('out', 'Withdrawal')], max_length=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(max_length=3)),
                ('fee_type', models.CharField(max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_record', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_paid', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail', models.CharField(choices=[('mpesa_ke', 'M-Pesa Kenya'), ('mpesa_tz', 'M-Pesa Tanzania'), ('mtn_ug', 'MTN MoMo Uganda'), ('mtn_rw', 'MTN MoMo Rwanda'), ('airtel_ke', 'Airtel Money Kenya'), ('airtel_tz', 'Airtel Tanzania'), ('airtel_ug', 'Airtel Uganda'), ('tigopesa', 'Tigo Pesa Tanzania'), ('telebirr', 'Telebirr Ethiopia'), ('bank_pesalink', 'PesaLink Kenya'), ('bank_swift', 'SWIFT International')], max_length=20)),
                ('label', models.CharField(max_length=60)),
                ('identifier', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=2)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='wallet.wallet')),
            ],
            options={
                'unique_together': {('wallet', 'rail', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CNY', 'Chinese Yuan'), ('AED', 'UAE Dirham'), ('INR', 'Indian Rupee'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('CHF', 'Swiss Franc'), ('ZAR', 'South African Rand'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('MUR', 'Mauritian Rupee')], max_length=3)),
                ('balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='wallet.wallet')),
            ],
            options={
                'ordering': ['currency'],
                'unique_together': {('wallet', 'currency')},
            },
        ),
    ]
