# Generated by Django 4.2.7 on 2026-06-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_settlement_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='settlement',
            field=models.ForeignKey(blank=True, help_text='Set when this fee is included in a settlement batch.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_records', to='wallet.feesettlement'),
        ),
    ]
