# Generated by Django 4.2.30 on 2026-07-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_flutterwave_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('mpesa_deposit', 'M-Pesa Deposit'), ('mpesa_withdraw', 'M-Pesa Withdrawal'), ('airtel_deposit', 'Airtel Money Deposit'), ('airtel_withdraw', 'Airtel Money Withdrawal'), ('bank_deposit', 'Bank Deposit'), ('bank_withdraw', 'Bank Withdrawal'), ('flw_card_deposit', 'Card Deposit (Flutterwave)'), ('flw_mobile_deposit', 'Mobile Money Deposit (Flutterwave)'), ('flw_bank_deposit', 'Bank Transfer Deposit (Flutterwave)'), ('flw_bank_payout', 'Bank Payout (Flutterwave)'), ('flw_mobile_payout', 'Mobile Money Payout (Flutterwave)'), ('exchange', 'Currency Exchange'), ('p2p_send', 'Transfer Sent'), ('p2p_receive', 'Transfer Received'), ('sandbox_reset', 'Sandbox Balance Reset (KYC Verified)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='walletlimit',
            name='daily_withdraw_kes',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='walletlimit',
            name='last_tier_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='walletlimit',
            name='monthly_limit_kes',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='walletlimit',
            name='per_txn_max_kes',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AlterField(
            model_name='walletlimit',
            name='tier_override',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Tier 0 — New Unverified'), (1, 'Tier 1 — Established Unverified'), (2, 'Tier 2 — KYC Verified'), (3, 'Tier 3 — Fully Verified')], null=True),
        ),
    ]
