# Generated by Django 4.2.7 on 2026-06-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_risk_mitigations'),
        ('wallet', '0007_new_models_and_fields'),
    ]

    operations = [
    ]
