# Generated by Django 4.2.7 on 2026-06-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_merge_20260617_0958'),
        ('wallet', '0008_new_models_and_fields'),
    ]

    operations = [
    ]
